PHI instruction need arguments but 0 was given

Traceback (most recent call last):
  File "conkas.py", line 114, in main
    traces = sym_exec.execute()
  File "/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/conkas/sym_exec/instructions/rattle_instructions.py", line 58, in inst_phi
    raise Exception
Exception
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
ANTLR runtime and generated code versions disagree: 4.9.2!=4.7.2
Analysing /sb/NanoLoanEngine.sol:Cosigner...
Nothing to analyse
Analysing /sb/NanoLoanEngine.sol:ERC721...
Nothing to analyse
Analysing /sb/NanoLoanEngine.sol:Engine...
Nothing to analyse
Analysing /sb/NanoLoanEngine.sol:NanoLoanEngine...
Analysing /sb/NanoLoanEngine.sol:Oracle...
Nothing to analyse
Analysing /sb/NanoLoanEngine.sol:Ownable...
Analysing /sb/NanoLoanEngine.sol:RpSafeMath...
Analysing /sb/NanoLoanEngine.sol:Token...
Nothing to analyse
Analysing /sb/NanoLoanEngine.sol:TokenLockable...
Vulnerability: Reentrancy. Maybe in function: withdrawTokens(address,address,uint256). PC: 0x2f4. Line number: 161.
Vulnerability: Reentrancy. Maybe in function: withdrawTokens(address,address,uint256). PC: 0x460. Line number: 163.
